### ISSUE TITLE
Unexpected unchecked appear?

### ISSUE THREAD

**Issue by oMojiko** [jaybjackie/HungryMe#107] opened 2022-11-24 04:48 UTC
![image](https://user-images.githubusercontent.com/91252217/203696658-871b9ca2-c529-4230-ae51-f94f19763928.png)

**Comment by zevenfox** [comment] 2022-11-25 10:15
Could you explain in more detail?
 I think this is bug but whatever I try to find "unchecked box" as you mention. It doesn't appear for my device.

**Comment by jaybjackie** [comment] 2022-11-25 10:21
I know what is he pointing at. But the 'unchecked' with the small rectangle is received together as an ingredients, it's a word that someone typing and we retrieve that API.

In another food you won't see 'unchecked' with small rectangle. It's not a bug. It is what user typing and we receive it from the API.

**Comment by zevenfox** [comment] 2022-11-25 10:31
Oh so that not a BUG but we receive it from API. Then we should close this issue. Thank Bezzu !

**Closed** 2022-11-25 12:37 UTC
